export const LANDING = '/'
export const SIGN_UP = '/signup'
export const SIGN_IN = '/signin'
export const EDIT_PROFILE = '/profile'
export const VIEW_PROFILE = '/profile/:uid'
export const NEW_PROJECT = '/project/new'
export const VIEW_PROJECT = '/project/:id'
export const EDIT_PROJECT = '/project/edit/:id'
